# Generated by Django 4.1.3 on 2022-12-10 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 10, 19, 9, 40, 789554, tzinfo=datetime.timezone.utc)),
        ),
    ]
